"""Reviev N1 migration

Revision ID: 5b7c249ff739
Revises: 392c94b3502d
Create Date: 2023-08-13 16:20:56.255115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7c249ff739'
down_revision = '392c94b3502d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
