"""Reviev N1.1 migration

Revision ID: be4556dcfdec
Revises: 5b7c249ff739
Create Date: 2023-08-13 16:57:26.803975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4556dcfdec'
down_revision = '5b7c249ff739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
