"""Add new models

Revision ID: d8dad9691e38
Revises: 22bc18737657
Create Date: 2023-08-06 08:46:25.183590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8dad9691e38'
down_revision = '22bc18737657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charityproject', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('charityproject', sa.Column('full_amount', sa.Integer(), nullable=False))
    op.add_column('charityproject', sa.Column('invested_amount', sa.Integer(), nullable=True))
    op.add_column('charityproject', sa.Column('fully_invested', sa.Boolean(), nullable=True))
    op.add_column('charityproject', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('charityproject', sa.Column('close_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charityproject', 'close_date')
    op.drop_column('charityproject', 'create_date')
    op.drop_column('charityproject', 'fully_invested')
    op.drop_column('charityproject', 'invested_amount')
    op.drop_column('charityproject', 'full_amount')
    op.drop_column('charityproject', 'description')
    # ### end Alembic commands ###
